set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions -Wall -Wextra -Wpedantic -Werror -fno-omit-frame-pointer")
set(CMAKE_LINKER_FLAGS "${CMAKE_LINKER_FLAGS} -fno-exceptions -Wall -Wextra -Wpedantic -Werror -fno-omit-frame-pointer")

find_program(CCACHE ccache)
if (CCACHE)
    message("Using ccache")
    set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE})
else ()
    message("ccache not found cannot use")
endif ()

find_program(CTIDY clang-tidy)
if (CTIDY)
    message("Using clang tidy")
    set(CMAKE_CXX_CLANG_TIDY ${CTIDY})
else ()
    message("Clang tidy not found")
endif ()
